[CONFIGURATION]
site_name|
site_label|Homelab
theme|exploration-light
relative_time|true
footer_links|false

[NAVIGATION]
bi-server|CasaOS|http://192.168.40.56:8080/
bi-film|Plex|http://192.168.40.56:32400/web/
bi-controller|RetroAssembly|http://192.168.40.56:4235
bi-graph-up|Plex Stats|http://192.168.40.56:8181/home
bi-book-half|AudioBookshelf|http://192.168.40.56:8081/
bi-database|PHPMyAdmin|/phpmyadmin/

[FOOTER]
Terms of Use|/legal/terms
Privacy Policy|/legal/privacy

[MODULES]
stats|true
livestats|false
weather|true
kpi|true
theme-selector|true

[LIVESTATS]
storage_budget| 10MB

[LOCATION]
lat|38.9717
lon|-95.2353
units|imperial

[BANNER]
enabled|false
dismissible|true
title|Welcome to The Vintage Gamers Dev Server
text|This development server is a live workspace for testing websites, applications, and new ideas. It provides a convenient environment for experimenting with projects before they are ready for production or public release.
text|It also serves as a central location for sharing files, hosting project assets, and providing access to resources needed by friends or collaborators. Whether it's a temporary test site or a long-term project, this server offers a flexible place to develop, store, and share content.


[KPI]
folders|false
files|false
plex_movies|true
plex_shows|true
plex_songs|true